name: tests

variables:
  - group: unittest-samples
  - name: self_location
    value: "self_location"
  - name: full_self_location
    value: "$(Agent.BuildDirectory)/$(self_location)"
  - name: samples_location
    value: "samples_location"
  - name: full_samples_location
    value: "$(Agent.BuildDirectory)/$(samples_location)"

resources:
  repositories:
  - repository: unittest-samples
    type: github
    name: $(unittest_samples_repository)
    ref: main
    endpoint: github-repo-sa
    trigger: none

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_9:
          python.version: "3.9"
        #Python3_10:
        #  python.version: "3.10"
        #Python3_11:
        #  python.version: "3.11"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - checkout: self
        fetchDepth: 1
        path: $(self_location)
      - checkout: unittest-samples
        fetchDepth: 1
        path: $(samples_location)
      - script: |
          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          sudo apt-get update
          sudo apt-get install -y libfuzzy-dev libfuzzy2
          sudo apt-get install -y libssl1.1 unace-nonfree python-lxml unrar build-essential libssl-dev wget swig
          wget -O /tmp/cybozulib.tar.gz https://assemblyline-support.s3.amazonaws.com/cybozulib.tar.gz
          mkdir -p /opt/al/support/extract
          tar -zxf /tmp/cybozulib.tar.gz -C /opt/al/support/extract
          wget -O /7z2201-linux-x86.tar.xz https://www.7-zip.org/a/7z2201-linux-x86.tar.xz
          mkdir /opt/7z && tar -xf /7z2201-linux-x86.tar.xz -C /opt/7z
          ln -s /opt/7z/7zzs /usr/bin/7zzs
          if [[ -f "$(pwd)/pkglist.txt" ]]; then
            grep -vE '^#' "$(pwd)/pkglist.txt" | xargs sudo apt install -y
          fi
          sudo rm -rf /var/lib/apt/lists/*
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir assemblyline assemblyline_v4_service
          [ -f $(pwd)/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/requirements.txt
          [ -f $(pwd)/tests/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/tests/requirements.txt
          sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip
        workingDirectory: $(full_self_location)
        displayName: Setup environment
      - script: |
          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          export REPO_NAME=${BUILD_REPOSITORY_NAME##*/}
          python -m pytest -p no:cacheprovider --durations=10 -rsx -vv --cov-report=xml --cov=${REPO_NAME/assemblyline-service-/}
        workingDirectory: $(full_self_location)
        displayName: Test
      - script: |
          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          python -m codecov
        workingDirectory: $(full_self_location)
        displayName: Upload Coverage
